name: CI

on: [push, pull_request]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.22"

            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker image and run unit tests
              run: docker-compose build

            - name: Run integrational test
              run: |
                  docker-compose -f docker-compose.yaml -f docker-compose.test.yaml up --exit-code-from test
